server:
  port: 8541
  servlet:
    context-path: /api/order

spring:
  application:
    name: service-order
  cloud:
    nacos:
      server-addr: 192.168.11.222:8848
      discovery:
        namespace: ccd13385-2994-4132-8bd2-2a6de5870884
      config:
        namespace: ccd13385-2994-4132-8bd2-2a6de5870884
    openfeign:
      client:
        config:
          default:
            logger-level: full
  config:
    import:
      - nacos:spzx-service-dev.yaml
feign:
  sentinel:
    enabled: true
logging:
  level:
    com.atguigu.spzx.client: debug

