# 配置服务端口号
server:
  port: 8501

# 配置数据库连接信息
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.11.222:3306/db_spzx?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  # Redis的相关配置
  data:
    redis:
      host: 192.168.11.222
      port: 6379
      password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#MyBatis的配置
mybatis:
  #配置Mapper映射文件存放的路径
  mapper-locations: classpath:mapper/*.xml
  configuration:
    #开启驼峰映射
    map-underscore-to-camel-case: true
    #在控制台打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spzx:
  intercept:
    exclude:
      urls:
        - /system/login
        - /system/validateCode
        # 开放swagger
        - /doc.html
        - /webjars/css/**
        - /webjars/js/**
        - /v3/api-docs/**
        - /favicon.ico
  minio:
    end-point: http://192.168.11.222:9001
    bucket-name: spzx
    access-key: admin
    secret-key: admin123456